// Default inline-CMS content. key -> { pl, en, kind }
// kind: text | html | image | video | color. DB overrides win when present.
export const DEFAULTS = {
  // --- nav ---
  "nav.forYou": { pl: "DLA CIEBIE", en: "FOR YOU", kind: "text" },
  "nav.forBiz": { pl: "DLA FIRM", en: "FOR BUSINESS", kind: "text" },
  "nav.products": { pl: "PRODUKTY", en: "PRODUCTS", kind: "text" },
  "nav.calendar": { pl: "KALENDARZ", en: "CALENDAR", kind: "text" },
  "nav.pricing": { pl: "CENNIK", en: "PRICING", kind: "text" },
  "nav.about": { pl: "O NAS", en: "ABOUT", kind: "text" },
  "nav.fleet": { pl: "FLOTA", en: "FLEET", kind: "text" },
  "nav.contact": { pl: "KONTAKT", en: "CONTACT", kind: "text" },
  // nav link targets (kind "url" -> not translated)
  "nav.forYou.href": { pl: "/rezerwacja", en: null, kind: "url" },
  "nav.forBiz.href": { pl: "#programy", en: null, kind: "url" },
  "nav.products.href": { pl: "/produkty", en: null, kind: "url" },
  "nav.calendar.href": { pl: "/kalendarz", en: null, kind: "url" },
  "nav.pricing.href": { pl: "/cennik", en: null, kind: "url" },
  "nav.about.href": { pl: "#instruktorzy", en: null, kind: "url" },
  "nav.fleet.href": { pl: "/flota", en: null, kind: "url" },
  "nav.contact.href": { pl: "/kontakt", en: null, kind: "url" },

  // --- hero ---
  "hero.video": { pl: "/assets/hero/HERO.webm", en: "", kind: "video" },
  "hero.eyebrow": { pl: "SZKOŁA JAZDY SPORTOWEJ I WYŚCIGOWEJ", en: "SPORT & RACING DRIVING SCHOOL", kind: "text" },
  "hero.title": { pl: "FASTLINE\nRACING ACADEMY", en: "FASTLINE\nRACING ACADEMY", kind: "text" },
  "hero.tag": { pl: "Poczuj emocje toru w najlepszych samochodach świata.", en: "Feel the thrill of the track in the world's finest cars.", kind: "text" },
  "hero.scrollHint": { pl: "PRZEWIŃ", en: "SCROLL", kind: "text" },

  // --- programs strip ---
  "programs.eyebrow": { pl: "FASTLINE RACING ACADEMY", en: "FASTLINE RACING ACADEMY", kind: "text" },
  "programs.title": { pl: "POCZUJ SIĘ JAK PRAWDZIWY KIEROWCA WYŚCIGOWY", en: "FEEL LIKE A REAL RACING DRIVER", kind: "text" },
  "programs.sub": { pl: "Sprawdź który program jest dla Ciebie najlepszy!", en: "Find the program that suits you best!", kind: "text" },
  "programs.cta": { pl: "WIĘCEJ", en: "MORE", kind: "text" },

  // --- fleet / cars ---
  "fleet.eyebrow": { pl: "NASZA FLOTA", en: "OUR FLEET", kind: "text" },
  "fleet.title": { pl: "STAJNIA WYJĄTKOWYCH SAMOCHODÓW", en: "A STABLE OF EXCEPTIONAL CARS", kind: "text" },
  "fleet.cta": { pl: "ZAPISZ SIĘ", en: "SIGN UP", kind: "text" },
  "fleet.more": { pl: "WIĘCEJ O MODELU", en: "MORE ABOUT THE MODEL", kind: "text" },
  "fleet.l_engine": { pl: "SILNIK", en: "ENGINE", kind: "text" },
  "fleet.l_power": { pl: "MOC", en: "POWER", kind: "text" },
  "fleet.l_torque": { pl: "MOMENT OBROTOWY", en: "TORQUE", kind: "text" },
  "fleet.l_speed": { pl: "PRĘDKOŚĆ MAKS.", en: "TOP SPEED", kind: "text" },

  // --- training / szkolenie ---
  "training.eyebrow": { pl: "SPORT DRIVING EXPERIENCE", en: "SPORT DRIVING EXPERIENCE", kind: "text" },
  "training.title": { pl: "SZKOLENIE JAZDY SPORTOWEJ", en: "SPORT DRIVING TRAINING", kind: "text" },
  "training.body": {
    pl: "Programy szkoleń i treningów jazdy sportowej na torze przeznaczone są dla wszystkich – zarówno dla profesjonalnych zawodników, którzy chcieliby poprawić swoje wyniki jak i dla osób, które chcą poczuć prawdziwe emocje jakie towarzyszą jeździe sportowym samochodem po torze.",
    en: "Our sport driving training programs on the track are designed for everyone – both professional drivers who want to improve their results and people who want to feel the real emotions of driving a sports car on a circuit.",
    kind: "html",
  },
  "training.cta": { pl: "ZAPISZ SIĘ", en: "SIGN UP", kind: "text" },
  "training.counterValue": { pl: "7500", en: "7500", kind: "text" },
  "training.counterLabel": { pl: "ZJEŻDŻONYCH OPON", en: "TYRES WORN OUT", kind: "text" },
  "training.sideImage": { pl: "/assets/covers/mariusz.webp", en: "", kind: "image" },
  "training.bandImage": { pl: "/assets/cars/porsche_2.webp", en: "", kind: "image" },

  // --- instructors ---
  "instructors.eyebrow": { pl: "FASTLINE RACING ACADEMY", en: "FASTLINE RACING ACADEMY", kind: "text" },
  "instructors.title": { pl: "POZNAJ NASZYCH INSTRUKTORÓW", en: "MEET OUR INSTRUCTORS", kind: "text" },
  "instructors.body": {
    pl: "Kadra Fastline Racing Academy to doświadczeni instruktorzy, z których każdy jest aktualnie uprawiającym motorsport czynnym zawodnikiem. Większość to utytułowani reprezentanci różnych dyscyplin świata motorsportu – wyścigów, rajdów, driftu, rallycrossu czy sim-racingu.",
    en: "The Fastline Racing Academy team consists of experienced instructors, each an active motorsport competitor. Most are decorated representatives of various motorsport disciplines – circuit racing, rallying, drifting, rallycross and sim-racing.",
    kind: "html",
  },

  // --- tracks ---
  "tracks.title": { pl: "WYBIERZ TOR", en: "CHOOSE A TRACK", kind: "text" },
  "tracks.pre": { pl: "TOR", en: "TRACK", kind: "text" },
  "tracks.l_country": { pl: "PAŃSTWO", en: "COUNTRY", kind: "text" },
  "tracks.l_turns": { pl: "LICZBA ZAKRĘTÓW", en: "NUMBER OF TURNS", kind: "text" },
  "tracks.l_length": { pl: "DŁUGOŚĆ", en: "LENGTH", kind: "text" },
  "tracks.l_width": { pl: "SZEROKOŚĆ", en: "WIDTH", kind: "text" },
  "tracks.u_meters": { pl: "METRÓW", en: "METERS", kind: "text" },

  // --- events ---
  "events.title": { pl: "NADCHODZĄCE WYDARZENIA", en: "UPCOMING EVENTS", kind: "text" },
  "events.cta": { pl: "ZOBACZ WSZYSTKIE", en: "SEE ALL", kind: "text" },
  "events.signup": { pl: "ZAPISZ SIĘ", en: "SIGN UP", kind: "text" },

  // --- cta buy ---
  "cta.eyebrow": { pl: "SPORT DRIVING EXPERIENCE", en: "SPORT DRIVING EXPERIENCE", kind: "text" },
  "cta.title": { pl: "PRZYCZEPNOŚCI!!", en: "GRIP ON!!", kind: "text" },
  "cta.buy": { pl: "KUP SZKOLENIE", en: "BUY TRAINING", kind: "text" },
  "cta.gift": { pl: "KUP PREZENT", en: "BUY A GIFT", kind: "text" },

  // --- footer ---
  "footer.eyebrow": { pl: "FASTLINE RACING ACADEMY", en: "FASTLINE RACING ACADEMY", kind: "text" },
  "footer.tagline": { pl: "SZKOLENIA JAZDY SPORTOWEJ I WYŚCIGOWEJ", en: "SPORT & RACING DRIVING TRAINING", kind: "text" },
  "footer.email": { pl: "kontakt@fastlineracingacademy.pl", en: "kontakt@fastlineracingacademy.pl", kind: "text" },
  "footer.phoneName": { pl: "Łukasz", en: "Łukasz", kind: "text" },
  "footer.phone": { pl: "+48 603 102 665", en: "+48 603 102 665", kind: "text" },
  "footer.rights": { pl: "© 2026 Fastline Racing Academy. Wszelkie prawa zastrzeżone.", en: "© 2026 Fastline Racing Academy. All rights reserved.", kind: "text" },

  // footer product columns are generated from the CMS products — only the column labels live here
  "footer.offer": { pl: "OFERTA", en: "OFFER", kind: "text" },
  "footer.pages": { pl: "NA STRONIE", en: "ON THE SITE", kind: "text" },
  "footer.privacy": { pl: "Polityka prywatności", en: "Privacy policy", kind: "text" },
  "footer.terms": { pl: "Regulamin płatności", en: "Payment terms", kind: "text" },
  // --- "O NAS" dropdown items (eyebrow + label; label kept untranslated where it's a proper name) ---
  "about.mariusz.pre": { pl: "SZKOŁA JAZDY SPORTOWEJ", en: "SPORT DRIVING SCHOOL", kind: "text" },
  "about.mariusz.label": { pl: "Mariusz Miękoś Racing", en: null, kind: "url" },
  "about.media.pre": { pl: "FASTLINE RACING ACADEMY", en: "FASTLINE RACING ACADEMY", kind: "text" },
  "about.media.label": { pl: "Media o nas", en: "Media about us", kind: "text" },
  "about.szkola.pre": { pl: "FASTLINE RACING ACADEMY", en: "FASTLINE RACING ACADEMY", kind: "text" },
  "about.szkola.label": { pl: "Szkoła jazdy sportowej", en: "Sport driving school", kind: "text" },

  // --- Mariusz Miękoś Racing page ---
  "mz.eyebrow": { pl: "SPORTOWIEC · BIZNESMEN · KIEROWCA WYŚCIGOWY", en: "ATHLETE · BUSINESSMAN · RACING DRIVER", kind: "text" },
  "mz.name": { pl: "MARIUSZ MIĘKOŚ", en: "MARIUSZ MIĘKOŚ", kind: "text" },
  "mz.role": { pl: "MARIUSZ MIĘKOŚ RACING", en: "MARIUSZ MIĘKOŚ RACING", kind: "text" },
  "mz.scrollHint": { pl: "PRZEWIŃ", en: "SCROLL", kind: "text" },
  "mz.slogan": { pl: "MISTRZ TORU", en: "MASTER OF THE TRACK", kind: "text" },
  "mz.hint": { pl: "NAJEDŹ, ABY ZAŁOŻYĆ KASK", en: "HOVER TO PUT THE HELMET ON", kind: "text" },
  "mz.face": { pl: "/assets/mariusz/face.webp", en: null, kind: "image" },
  "mz.kask": { pl: "/assets/mariusz/kask.webp", en: null, kind: "image" },
  "mz.sign": { pl: "/assets/mariusz/signature-red.webp", en: null, kind: "image" },

  "mz.bioEyebrow": { pl: "FASTLINE RACING ACADEMY", en: "FASTLINE RACING ACADEMY", kind: "text" },
  "mz.bioTitle": { pl: "OŚMIOKROTNY MISTRZ POLSKI", en: "EIGHT-TIME POLISH CHAMPION", kind: "text" },
  "mz.bio1": { pl: "W barwach Fastline Racing w latach 2020, 2019, 2018 i 2017 za kierownicą Lamborghini Huracán Supertrofeo i Porsche 911 GT3 Cup zdobył osiem tytułów Wyścigowego Mistrza Polski.", en: "", kind: "html" },
  "mz.bio2": { pl: "Na swoim koncie ma również starty w prestiżowym 24-godzinnym wyścigu w Dubaju, dwukrotnie ukończonym na podium, liczne tytuły wicemistrzowskie w czempionacie narodowym WSMP, DSMP i w europejskiej serii Porsche GT3 Cup Central Europe.", en: "", kind: "html" },
  "mz.bio3": { pl: "Zawodnik Automobilklubu Wielkopolskiego. Kierowca zespołu Fastline Racing, GT3 Poland, wcześniej zespołów Forch Racing, Lukas Motorsport, Seat Sport Polska, Fiat Auto Poland.", en: "", kind: "html" },
  "mz.bio4": { pl: "Założyciel Fastline Racing Academy — dzięki sukcesom za kierownicą wyścigówek stara się wykorzystać doświadczenie z torów i rozwijać programy treningowe jazdy sportowej i wyścigowej.", en: "", kind: "html" },
  "mz.bio5": { pl: "W równolegle prowadzonej agencji Fastline Advertising realizuje unikatowe eventy na torach w cyklu Sport Driving Experience, w ramach których dzieli się swoją wiedzą i doświadczeniem na temat szybkiej i skutecznej jazdy sportowej na torze.", en: "", kind: "html" },
  "mz.bio6": { pl: "Doświadczony instruktor, szef teamu instruktorów Fastline Racing Academy. Ukończył programy Audi, Maserati, Porsche i Subaru; od 2008 pracował dla tych marek oraz prowadził niezależnie eventy na torach, m.in. Orange Business Extreme, Nokia, Cisco, Porsche, Orlen, Verva Racing Team. Instruktor Porsche Driving Experience na Silesiaring w sezonie 2017.", en: "", kind: "html" },
  "mz.bio7": { pl: "Pasjonat sportów ekstremalnych — aktywnie uprawia kiteboarding, windsurfing, snowboarding, freeriding, XTB, MTB i downhill. Prywatnie mąż Magdy oraz ojciec Leny, Mateusza, Mikołaja i Filipa.", en: "", kind: "html" },

  "mz.resultsEyebrow": { pl: "OSIĄGNIĘCIA", en: "ACHIEVEMENTS", kind: "text" },
  "mz.resultsTitle": { pl: "KARIERA TOROWA I WYNIKI", en: "TRACK CAREER & RESULTS", kind: "text" },
  "mz.results": {
    pl: [
      "2020 · Mistrz Polski WSMP +3500 — Lamborghini Huracán Supertrofeo / Porsche GT3 Cup 991 — Fastline Racing Academy / GT3 Poland",
      "2019 · Mistrz Polski DSMP Hour Race — klasyfikacja indywidualna — Fastline Racing Academy / GT3 Poland",
      "2019 · Mistrz Polski DSMP Hour Race — klasyfikacja zespołowa (z Arturem Janoszem) — Fastline Racing Academy / GT3 Poland",
      "2019 · Mistrz Polski WSMP +3500 — Fastline Racing Academy / GT3 Poland",
      "2018 · Mistrz Polski DSMP Hour Race — klasyfikacja indywidualna — Fastline Racing Academy / GT3 Poland",
      "2018 · Mistrz Polski DSMP Hour Race — klasyfikacja zespołowa — Fastline Racing Academy / GT3 Poland",
      "2018 · I Wicemistrz Polski WSMP — Fastline Racing Academy / GT3 Poland",
      "2017 · Mistrz Polski DSMP Hour Race — klasyfikacja indywidualna — Fastline Racing Academy / GT3 Poland",
      "2017 · Mistrz Polski DSMP Hour Race — klasyfikacja zespołowa (z Mariuszem Urbańskim) — Fastline Racing Academy / GT3 Poland",
      "2012 · Uczestnik Dunlop 24H Dubai Race — Porsche GT3 Cup — Forch Racing",
      "2012 · Wicemistrz Pucharu Porsche GT3 Cup Central Europe — Forch Racing",
      "2012 · Wicemistrz Polski DSMP w klasie 4 — Porsche GT3 Cup — Forch Racing",
      "2011 · Wicemistrz Polski DSMP w klasie 4 — Porsche GT3 Cup — Forch Racing",
      "2011 · Wicemistrz Polski DSMP w klasyfikacji generalnej — Porsche GT3 Cup — Forch Racing",
      "2010 · Wicemistrz Polski DSMP w klasie 4 — Porsche GT3 Cup — Forch Racing",
      "2010 · Wicemistrz Polski DSMP w klasyfikacji generalnej — Porsche GT3 Cup — Forch Racing",
      "2010 · 5. miejsce w klasyfikacji generalnej Dunlop 24H Dubai — Forch Racing",
      "2010 · 3. miejsce w klasie A6 Dunlop 24H Dubai — Forch Racing",
      "2009 · 24H Dubai Race — 20. miejsce w kl. gen. — Porsche 997 GT3 Cup — Lukas Motorsport",
      "2008 · Wicemistrz Polski WSMP — Porsche 997 GT3 Cup — Lukas Motorsport",
      "2008 · 1. miejsce w klasyfikacji Toyo — 24H Dubai Race — VW Golf V — Pachura Motorsport",
      "2007 · Wicemistrzostwo Polski DSMP w klasyfikacji generalnej — Seat Leon Supercopa — Seat Sport Polska",
      "2007 · Mistrzostwo Polski DSMP H-3500 — Seat Leon Supercopa — Seat Sport Polska",
      "1994–1996 · Udział w WSMP w Pucharze Fiata Cinquecento",
      "1987–1988 · Udział w Samochodowych Mistrzostwach Polski (WSMP, GSMP) — Fiat 126 klasa N",
    ].join("\n"),
    en: null,
    kind: "url",
  },

  "mz.galleryEyebrow": { pl: "NA TORZE", en: "ON THE TRACK", kind: "text" },
  "mz.gallery1": { pl: "/assets/mariusz/photo1.webp", en: null, kind: "image" },
  "mz.gallery2": { pl: "/assets/mariusz/photo2.webp", en: null, kind: "image" },
  "mz.gallery1cap": { pl: "Lamborghini Huracán Supertrofeo", en: "Lamborghini Huracán Supertrofeo", kind: "text" },
  "mz.gallery1desc": { pl: "Za kierownicą Lamborghini Huracán Supertrofeo w barwach Fastline Racing Mariusz sięgał po kolejne tytuły Mistrza Polski — auto, którym na co dzień szkoli na torze najlepszych.", en: "", kind: "html" },
  "mz.gallery2cap": { pl: "Porsche 911 GT3 Cup", en: "Porsche 911 GT3 Cup", kind: "text" },
  "mz.gallery2desc": { pl: "Wieloletnie starty Porsche 911 GT3 Cup — od 24-godzinnego wyścigu w Dubaju po podia mistrzostw Polski — to fundament doświadczenia, którym Mariusz dzieli się z kursantami.", en: "", kind: "html" },

  "mz.ctaTitle": { pl: "TRENUJ Z MISTRZEM", en: "TRAIN WITH THE CHAMPION", kind: "text" },
  "mz.ctaSub": { pl: "Dołącz do Fastline Racing Academy i poczuj tor pod okiem Mariusza.", en: "Join Fastline Racing Academy and feel the track under Mariusz's guidance.", kind: "text" },
  "mz.ctaBtn": { pl: "ZAPISZ SIĘ", en: "SIGN UP", kind: "text" },

  // --- Media o nas page ---
  "media.eyebrow": { pl: "PRASA · WYWIADY · WIDEO", en: "PRESS · INTERVIEWS · VIDEO", kind: "text" },
  "media.title": { pl: "MEDIA O NAS", en: "MEDIA ABOUT US", kind: "text" },
  "media.intro": { pl: "O Mariuszu Miękosiu, początkach Fastline Racing Academy, projekcie Heels on the Track i naszych startach na torach całej Europy — okiem dziennikarzy.", en: "About Mariusz Miękoś, the beginnings of Fastline Racing Academy, the Heels on the Track project and our races across Europe — through the eyes of journalists.", kind: "html" },
  "media.readmore": { pl: "CZYTAJ", en: "READ", kind: "text" },
  "media.empty": { pl: "Brak publikacji.", en: "No publications yet.", kind: "text" },

  // --- Szkoła jazdy sportowej page (/o-szkole) ---
  "sz.video": { pl: "/assets/szkola/hero.webm", en: "", kind: "video" },
  "sz.eyebrow": { pl: "FASTLINE RACING ACADEMY", en: "FASTLINE RACING ACADEMY", kind: "text" },
  "sz.title": { pl: "SZKOŁA JAZDY SPORTOWEJ", en: "SPORT DRIVING SCHOOL", kind: "text" },
  "sz.sub": { pl: "Szkolenie jazdy sportowej i wyścigowej w najlepszych wyścigówkach świata.", en: "Sport and racing driving training in the world's finest race cars.", kind: "text" },
  "sz.scrollHint": { pl: "PRZEWIŃ", en: "SCROLL", kind: "text" },
  "sz.hudLabel": { pl: "TELEMETRIA", en: "TELEMETRY", kind: "text" },

  // intro / manifest
  "sz.introEyebrow": { pl: "O SZKOLE", en: "ABOUT THE SCHOOL", kind: "text" },
  "sz.introTitle": { pl: "PRZEDSIĘWZIĘCIE, JAKIEGO W POLSCE NIE BYŁO", en: "A VENTURE POLAND HAD NEVER SEEN BEFORE", kind: "text" },
  "sz.p1": { pl: "Wykorzystując swoje wieloletnie doświadczenie zdobyte w wyścigach samochodowych, stworzyliśmy przedsięwzięcie, jakiego wcześniej w Polsce nie było — szkolenie jazdy sportowej i wyścigowej w najlepszych wyścigówkach świata.", en: "Drawing on our many years of experience gained in motor racing, we created a venture Poland had never seen before — sport and racing driving training in the world's finest race cars.", kind: "html" },
  "sz.p2": { pl: "Celem Fastline Racing Academy jest przekazanie wiedzy, rozwój umiejętności jazdy sportowej i wyścigowej oraz umożliwienie realizacji marzeń i pasji zamiłowania do motosportu.", en: "The goal of Fastline Racing Academy is to pass on knowledge, develop sport and racing driving skills, and make it possible to realise dreams and a passion for motorsport.", kind: "html" },
  "sz.introPhoto": { pl: "/assets/szkola/onas1.webp", en: null, kind: "image" },
  "sz.statValue": { pl: "9", en: "9", kind: "text" },
  "sz.statLabel": { pl: "TYTUŁÓW MISTRZA POLSKI", en: "POLISH CHAMPION TITLES", kind: "text" },

  // two machines
  "sz.carsEyebrow": { pl: "MASZYNY TOROWE", en: "TRACK MACHINES", kind: "text" },
  "sz.carsTitle": { pl: "SUROWE. BEZ HOMOLOGACJI. STWORZONE DO TORU.", en: "RAW. NO HOMOLOGATION. BUILT FOR THE TRACK.", kind: "text" },
  "sz.carsBody": { pl: "Lamborghini Huracán Super Trofeo oraz Porsche 911 GT3 Cup to samochody stworzone tylko i wyłącznie do jazdy torowej, nie posiadające homologacji oraz bardzo surowe i trudne w prowadzeniu.", en: "The Lamborghini Huracán Super Trofeo and the Porsche 911 GT3 Cup are cars built solely and exclusively for track driving — with no road homologation, and very raw and demanding to drive.", kind: "html" },
  "sz.car1name": { pl: "LAMBORGHINI HURACÁN", en: "LAMBORGHINI HURACÁN", kind: "text" },
  "sz.car1sub": { pl: "SUPER TROFEO", en: "SUPER TROFEO", kind: "text" },
  "sz.car2name": { pl: "PORSCHE 911", en: "PORSCHE 911", kind: "text" },
  "sz.car2sub": { pl: "GT3 CUP", en: "GT3 CUP", kind: "text" },
  "sz.tag1": { pl: "BEZ HOMOLOGACJI", en: "NO HOMOLOGATION", kind: "text" },
  "sz.tag2": { pl: "TYLKO TOR", en: "TRACK ONLY", kind: "text" },
  "sz.tag3": { pl: "SUROWE W PROWADZENIU", en: "RAW TO DRIVE", kind: "text" },

  // McRae quote
  "sz.quotePre": { pl: "Straight roads are for", en: "Straight roads are for", kind: "text" },
  "sz.quoteRed1": { pl: "fast cars", en: "fast cars", kind: "text" },
  "sz.quoteMid": { pl: ", turns are for", en: ", turns are for", kind: "text" },
  "sz.quoteRed2": { pl: "fast drivers", en: "fast drivers", kind: "text" },
  "sz.quoteAuthor": { pl: "COLIN McRAE", en: "COLIN McRAE", kind: "text" },

  // stages / ścieżka rozwoju
  "sz.stagesEyebrow": { pl: "ŚCIEŻKA ROZWOJU", en: "YOUR PROGRESSION", kind: "text" },
  "sz.stagesTitle": { pl: "OD PODSTAW DO PODIUM", en: "FROM THE BASICS TO THE PODIUM", kind: "text" },
  "sz.stagesHint": { pl: "WYBIERZ BIEG", en: "SELECT A GEAR", kind: "text" },
  "sz.s1name": { pl: "STAGE 1", en: "STAGE 1", kind: "text" },
  "sz.s1tag": { pl: "OD PODSTAW", en: "FROM THE BASICS", kind: "text" },
  "sz.s1desc": { pl: "Pierwszy kontakt z torem. Poznajesz podstawy techniki jazdy sportowej, tor wyścigowy i pracę za kierownicą prawdziwej wyścigówki — bezpiecznie i pod okiem instruktora-zawodnika.", en: "Your first contact with the track. You learn the basics of sport driving technique, the racing circuit and working behind the wheel of a real race car — safely, guided by a competitor-instructor.", kind: "html" },
  "sz.s2name": { pl: "STAGE 2", en: "STAGE 2", kind: "text" },
  "sz.s2tag": { pl: "DLA ŚREDNIO-ZAAWANSOWANYCH", en: "FOR THE INTERMEDIATE", kind: "text" },
  "sz.s2desc": { pl: "Rozwijasz płynność i szybkość. Trail braking, dobór idealnego toru jazdy i praca z przyczepnością na wyższym poziomie — zaczynasz naprawdę atakować zakręty.", en: "You develop smoothness and speed. Trail braking, choosing the ideal racing line and working with grip at a higher level — you start to really attack the corners.", kind: "html" },
  "sz.s3name": { pl: "STAGE 3", en: "STAGE 3", kind: "text" },
  "sz.s3tag": { pl: "DLA ZAWODNIKÓW", en: "FOR COMPETITORS", kind: "text" },
  "sz.s3desc": { pl: "Poziom wyścigowy. Ściganie się koło w koło, starty, walka o setne sekundy i przygotowanie do startów w prawdziwych zawodach za kierownicą Porsche GT3 Cup i Lamborghini Super Trofeo.", en: "Racing level. Wheel-to-wheel battles, race starts, fighting for hundredths of a second and preparing for real competition behind the wheel of the Porsche GT3 Cup and Lamborghini Super Trofeo.", kind: "html" },
  "sz.s4name": { pl: "ICE", en: "ICE", kind: "text" },
  "sz.s4tag": { pl: "DRIVING EXPERIENCE", en: "DRIVING EXPERIENCE", kind: "text" },
  "sz.s4desc": { pl: "Pełna kontrola pojazdu na lodzie i śniegu. Kontrolowany poślizg, precyzja i pewność w najtrudniejszych warunkach — szkoła, która procentuje na każdej nawierzchni.", en: "Full vehicle control on ice and snow. Controlled drift, precision and confidence in the toughest conditions — a school that pays off on every surface.", kind: "html" },
  "sz.stagesCta": { pl: "ZOBACZ OFERTĘ", en: "SEE THE OFFER", kind: "text" },

  // closing band
  "sz.bandEyebrow": { pl: "DROGA OTWARTA", en: "THE ROAD IS OPEN", kind: "text" },
  "sz.bandTitle": { pl: "SZEROKO OTWARTA DROGA", en: "A WIDE-OPEN ROAD", kind: "text" },
  "sz.bandBody": { pl: "Dzięki szkole droga do rozwoju umiejętności sport driving lub rozpoczęcia ścigania się na wyższym poziomie jest już teraz szeroko otwarta.", en: "Thanks to the school, the path to developing your sport-driving skills — or to start racing at a higher level — is now wide open.", kind: "html" },
  "sz.bandPhoto": { pl: "/assets/szkola/onas2.webp", en: null, kind: "image" },

  // CTA
  "sz.ctaEyebrow": { pl: "SPORT DRIVING EXPERIENCE", en: "SPORT DRIVING EXPERIENCE", kind: "text" },
  "sz.ctaTitle": { pl: "ZACHĘCAMY DO KONTAKTU", en: "GET IN TOUCH WITH US", kind: "text" },
  "sz.ctaSub": { pl: "Skontaktuj się z nami, aby omówić szczegóły szkolenia i dobrać program idealny dla Ciebie.", en: "Contact us to discuss the details of the training and choose the program that's perfect for you.", kind: "text" },
  "sz.ctaBuy": { pl: "KUP SZKOLENIE", en: "BUY TRAINING", kind: "text" },
  "sz.ctaContact": { pl: "KONTAKT", en: "CONTACT", kind: "text" },

  // --- Flota page (/flota) ---
  "flota.video": { pl: "/assets/flota/hero.webm", en: "", kind: "video" },
  "flota.eyebrow": { pl: "STAJNIA FASTLINE RACING ACADEMY", en: "THE FASTLINE RACING ACADEMY STABLE", kind: "text" },
  "flota.title": { pl: "NASZA FLOTA", en: "OUR FLEET", kind: "text" },
  "flota.sub": { pl: "Najlepsze auta sportowe i wyścigowe — gotowe, byś usiadł za kierownicą i poczuł prawdziwy tor.", en: "The finest sport and race cars — ready for you to take the wheel and feel a real circuit.", kind: "text" },
  "flota.scrollHint": { pl: "PRZEWIŃ", en: "SCROLL", kind: "text" },
  // intro text block
  "flota.introEyebrow": { pl: "STAJNIA", en: "THE STABLE", kind: "text" },
  "flota.introTitle": { pl: "MASZYNY, KTÓRE ROBIĄ RÓŻNICĘ", en: "MACHINES THAT MAKE THE DIFFERENCE", kind: "text" },
  "flota.introBody": { pl: "Od zwinnej Alpine A110, przez króla toru Toyotę GR Supra, po bezkompromisowe Porsche 911 GTS — każde auto w naszej stajni ma jeden cel: dać Ci maksimum emocji i nauczyć Cię prawdziwej jazdy sportowej. Wybierz maszynę, wybierz pakiet i zarezerwuj swój termin na torze.", en: "From the nimble Alpine A110, through the track king Toyota GR Supra, to the uncompromising Porsche 911 GTS — every car in our stable has one goal: to give you maximum emotion and teach you real sport driving. Choose the machine, choose the package and book your date on the track.", kind: "html" },
  // slider
  "flota.sliderEyebrow": { pl: "WYBIERZ AUTO", en: "CHOOSE A CAR", kind: "text" },
  "flota.sliderTitle": { pl: "WYBIERZ TWOJE WYMARZONE AUTO", en: "CHOOSE YOUR DREAM CAR", kind: "text" },
  "flota.back": { pl: "WSTECZ", en: "BACK", kind: "text" },
  "flota.more": { pl: "WIĘCEJ O MODELU", en: "MORE ABOUT THE MODEL", kind: "text" },
  "flota.choose": { pl: "WYBIERAM", en: "I CHOOSE", kind: "text" },
  "flota.from": { pl: "od", en: "from", kind: "text" },
  // full-stable grid
  "flota.gridEyebrow": { pl: "PEŁNA STAJNIA", en: "THE FULL STABLE", kind: "text" },
  "flota.gridTitle": { pl: "CAŁA NASZA FLOTA", en: "OUR ENTIRE FLEET", kind: "text" },
  "flota.gridSub": { pl: "Kliknij auto, aby zobaczyć je w konfiguratorze powyżej.", en: "Click a car to see it in the configurator above.", kind: "text" },
  // custom car
  "flota.customEyebrow": { pl: "MASZ SWOJE AUTO?", en: "GOT YOUR OWN CAR?", kind: "text" },
  "flota.customName": { pl: "WŁASNE AUTO", en: "YOUR OWN CAR", kind: "text" },
  "flota.customDesc": { pl: "Przyjedź na tor swoim samochodem i szkól się pod okiem naszych instruktorów-zawodników. Wybierz pakiet i zarezerwuj termin.", en: "Come to the track in your own car and train under the eye of our competitor-instructors. Choose a package and book a date.", kind: "html" },
  "flota.customBtn": { pl: "WYBIERAM SWOJE AUTO", en: "I CHOOSE MY OWN CAR", kind: "text" },
  // custom-car package prices (kind url -> numbers, not translated). p1/p5 derived, p3/p6/p9 z cennika
  "flota.custom.p1": { pl: "550", en: null, kind: "url" },
  "flota.custom.p3": { pl: "1450", en: null, kind: "url" },
  "flota.custom.p5": { pl: "2050", en: null, kind: "url" },
  "flota.custom.p6": { pl: "2350", en: null, kind: "url" },
  "flota.custom.p9": { pl: "3350", en: null, kind: "url" },
  // custom-car Poznań prices (own vehicle Łódź + 1200 zł Poznań surcharge)
  "flota.custom.p1_pozn": { pl: "1750", en: null, kind: "url" },
  "flota.custom.p3_pozn": { pl: "2650", en: null, kind: "url" },
  "flota.custom.p5_pozn": { pl: "3250", en: null, kind: "url" },
  "flota.custom.p6_pozn": { pl: "3550", en: null, kind: "url" },
  "flota.custom.p9_pozn": { pl: "4550", en: null, kind: "url" },

  // booking flow (fuel-fill wizard)
  "flota.bk.title": { pl: "REZERWACJA", en: "BOOKING", kind: "text" },
  // what is actually being booked — shown at the top of the configurator
  "flota.bk.product": { pl: "SPORT DRIVING EXPERIENCE", en: "SPORT DRIVING EXPERIENCE", kind: "text" },
  "flota.bk.productSub": { pl: "SZKOLENIE Z JAZDY SPORTOWEJ", en: "SPORT DRIVING TRAINING", kind: "text" },
  "flota.bk.configTitle": { pl: "KONFIGURATOR JAZDY", en: "DRIVE CONFIGURATOR", kind: "text" },
  "flota.bk.autoTitle": { pl: "WYBIERZ AUTO", en: "CHOOSE A CAR", kind: "text" },
  "flota.bk.autoSub": { pl: "Wybierz samochód, którym chcesz jeździć po torze.", en: "Pick the car you want to drive on the track.", kind: "text" },
  "flota.bk.sAuto": { pl: "AUTO", en: "CAR", kind: "text" },
  "flota.bk.chosenCar": { pl: "AUTO", en: "CAR", kind: "text" },
  "flota.bk.chosenDate": { pl: "TERMIN", en: "DATE", kind: "text" },
  "flota.bk.s1": { pl: "PAKIET", en: "PACKAGE", kind: "text" },
  "flota.bk.s2": { pl: "TERMIN", en: "DATE", kind: "text" },
  "flota.bk.s3": { pl: "DANE", en: "DETAILS", kind: "text" },
  "flota.bk.s4": { pl: "PŁATNOŚĆ", en: "PAYMENT", kind: "text" },
  "flota.bk.pkgTitle": { pl: "WYBIERZ PAKIET", en: "CHOOSE A PACKAGE", kind: "text" },
  "flota.bk.pkgSub": { pl: "Im więcej sesji, tym więcej czasu na torze i lepsza cena za sesję.", en: "The more sessions, the more track time and a better price per session.", kind: "text" },
  "flota.bk.carLabel": { pl: "Twoje auto", en: "Your car", kind: "text" },
  "flota.bk.carPh": { pl: "np. BMW M4 Competition", en: "e.g. BMW M4 Competition", kind: "text" },
  "flota.bk.termTitle": { pl: "WYBIERZ TERMIN", en: "CHOOSE A DATE", kind: "text" },
  "flota.bk.termSub": { pl: "Dostępne terminy na najbliższych torach.", en: "Available dates at upcoming circuits.", kind: "text" },
  "flota.bk.noTerms": { pl: "Brak dostępnych terminów — skontaktuj się z nami, dobierzemy termin indywidualnie.", en: "No available dates — contact us and we'll arrange one individually.", kind: "text" },
  "flota.bk.noDate": { pl: "BEZ DATY", en: "NO DATE", kind: "text" },
  "flota.bk.noDateSub": { pl: "Termin ustalimy indywidualnie", en: "We'll arrange the date individually", kind: "text" },
  "flota.bk.dataTitle": { pl: "TWOJE DANE", en: "YOUR DETAILS", kind: "text" },
  "flota.bk.dataSub": { pl: "Potrzebujemy ich do potwierdzenia rezerwacji i płatności.", en: "We need these to confirm your booking and payment.", kind: "text" },
  "flota.bk.name": { pl: "Imię i nazwisko", en: "Full name", kind: "text" },
  "flota.bk.email": { pl: "E-mail", en: "E-mail", kind: "text" },
  "flota.bk.phone": { pl: "Telefon", en: "Phone", kind: "text" },
  "flota.bk.note": { pl: "Uwagi (opcjonalnie)", en: "Notes (optional)", kind: "text" },
  "flota.bk.next": { pl: "DALEJ", en: "NEXT", kind: "text" },
  "flota.bk.prev": { pl: "WSTECZ", en: "BACK", kind: "text" },
  "flota.bk.pay": { pl: "ZAPŁAĆ I ZAREZERWUJ", en: "PAY & BOOK", kind: "text" },
  "flota.bk.summary": { pl: "PODSUMOWANIE", en: "SUMMARY", kind: "text" },
  "flota.bk.total": { pl: "RAZEM", en: "TOTAL", kind: "text" },
  "flota.bk.processing": { pl: "TANKOWANIE…", en: "FUELLING UP…", kind: "text" },
  "flota.bk.doneTitle": { pl: "ZATANKOWANE — OPŁACONE!", en: "FULL TANK — PAID!", kind: "text" },
  "flota.bk.thanks": { pl: "Dziękujemy! Twoja rezerwacja jest potwierdzona. Wyślemy szczegóły na podany e-mail.", en: "Thank you! Your booking is confirmed. We'll send the details to the e-mail you provided.", kind: "html" },
  "flota.bk.close": { pl: "ZAMKNIJ", en: "CLOSE", kind: "text" },
  "flota.bk.demoNote": { pl: "Płatność demonstracyjna — WooCommerce zostanie podłączone wkrótce.", en: "Demo payment — WooCommerce will be connected soon.", kind: "text" },

  // --- Produkty page (/produkty + /produkty/:slug) — products come from the CMS "Produkty" tab ---
  "prod.eyebrow": { pl: "OFERTA FASTLINE RACING ACADEMY", en: "THE FASTLINE RACING ACADEMY OFFER", kind: "text" },
  "prod.title": { pl: "PRODUKTY", en: "PRODUCTS", kind: "text" },
  "prod.sub": { pl: "Od pierwszego okrążenia po testy wyścigówką. Wybierz program, który pasuje do Twojego poziomu — każdy prowadzą instruktorzy będący czynnymi zawodnikami.", en: "From your first lap to race-car test days. Pick the program that fits your level — every one is run by instructors who are active competitors.", kind: "html" },
  "prod.count": { pl: "PROGRAMÓW W OFERCIE", en: "PROGRAMS ON OFFER", kind: "text" },
  "prod.go": { pl: "POZNAJ SZCZEGÓŁY", en: "SEE THE DETAILS", kind: "text" },
  "prod.goExt": { pl: "PRZEJDŹ NA STRONĘ", en: "GO TO THE SITE", kind: "text" },
  "prod.ctaEyebrow": { pl: "NIE WIESZ, CO WYBRAĆ?", en: "NOT SURE WHICH TO PICK?", kind: "text" },
  "prod.ctaTitle": { pl: "ZACZNIJ OD TORU", en: "START ON THE TRACK", kind: "text" },
  "prod.ctaSub": { pl: "Wybierz auto i pakiet w konfiguratorze albo zobacz najbliższe terminy w kalendarzu.", en: "Choose a car and a package in the configurator, or check the next dates in the calendar.", kind: "html" },
  "prod.ctaBook": { pl: "KONFIGURATOR JAZDY", en: "DRIVE CONFIGURATOR", kind: "text" },
  "prod.ctaCal": { pl: "KALENDARZ", en: "CALENDAR", kind: "text" },
  // product page
  "prod.aboutLabel": { pl: "O PROGRAMIE", en: "ABOUT THE PROGRAM", kind: "text" },
  "prod.theory": { pl: "CZĘŚĆ TEORETYCZNA", en: "THE THEORY", kind: "text" },
  "prod.practice": { pl: "CZĘŚĆ PRAKTYCZNA", en: "THE PRACTICE", kind: "text" },
  "prod.learn": { pl: "CZEGO SIĘ NAUCZYSZ", en: "WHAT YOU WILL LEARN", kind: "text" },
  "prod.includes": { pl: "W PAKIECIE", en: "WHAT'S INCLUDED", kind: "text" },
  "prod.packages": { pl: "PAKIETY", en: "PACKAGES", kind: "text" },
  "prod.pick": { pl: "REZERWUJ", en: "BOOK", kind: "text" },
  "prod.places": { pl: "MIEJSCE", en: "LOCATION", kind: "text" },
  "prod.level": { pl: "POZIOM", en: "LEVEL", kind: "text" },
  "prod.book": { pl: "ZAREZERWUJ", en: "BOOK NOW", kind: "text" },
  // info-only products (simulator): no buying, just contact
  "prod.stages": { pl: "ETAPY SZKOLENIA", en: "TRAINING STAGES", kind: "text" },
  "prod.infoSub": { pl: "Chcesz wiedzieć więcej o szkoleniach na symulatorze? Napisz do nas — dobierzemy program pod Twój poziom i cel.", en: "Want to know more about simulator training? Write to us — we'll match the program to your level and goal.", kind: "html" },
  "prod.contact": { pl: "KONTAKT", en: "CONTACT", kind: "text" },
  "prod.more": { pl: "WIĘCEJ", en: "MORE", kind: "text" },
  "prod.back": { pl: "WSZYSTKIE PRODUKTY", en: "ALL PRODUCTS", kind: "text" },



  // --- Kontakt page (/kontakt) — form goes through the `contact` edge function (Resend) ---
  "kon.eyebrow": { pl: "NAPISZ LUB ZADZWOŃ", en: "WRITE OR CALL", kind: "text" },
  "kon.title": { pl: "KONTAKT", en: "CONTACT", kind: "text" },
  "kon.sub": { pl: "Szkolenia indywidualne, vouchery, eventy firmowe — odezwij się, a dobierzemy program i termin pod Ciebie.", en: "Individual training, vouchers, corporate events — get in touch and we'll match the program and the date to you.", kind: "html" },
  "kon.mailLabel": { pl: "E-MAIL", en: "E-MAIL", kind: "text" },
  "kon.email": { pl: "racingacademy@fastline.pl", en: "racingacademy@fastline.pl", kind: "text" },
  "kon.mailHint": { pl: "Odpowiadamy zwykle w ciągu jednego dnia roboczego.", en: "We usually reply within one business day.", kind: "text" },
  "kon.p1.role": { pl: "SZKOLENIA INDYWIDUALNE / VOUCHERY", en: "INDIVIDUAL TRAINING / VOUCHERS", kind: "text" },
  "kon.p1.name": { pl: "ŁUKASZ", en: "ŁUKASZ", kind: "text" },
  "kon.p1.phone": { pl: "+48 603 102 665", en: "+48 603 102 665", kind: "text" },
  "kon.p2.role": { pl: "EVENTY FIRMOWE", en: "CORPORATE EVENTS", kind: "text" },
  "kon.p2.name": { pl: "MARIUSZ", en: "MARIUSZ", kind: "text" },
  "kon.p2.phone": { pl: "+48 601 280 520", en: "+48 601 280 520", kind: "text" },
  "kon.company": { pl: "FASTLINE EVENTS SP. Z O.O.", en: "FASTLINE EVENTS SP. Z O.O.", kind: "text" },
  "kon.companyNote": { pl: "Szkolenia jazdy sportowej i wyścigowej na torach w Polsce i Europie.", en: "Sport and racing driving training on circuits in Poland and Europe.", kind: "html" },
  "kon.formTitle": { pl: "NAPISZ DO NAS", en: "WRITE TO US", kind: "text" },
  "kon.formSub": { pl: "Wypełnij formularz — odpowiemy na podany e-mail.", en: "Fill in the form — we'll reply to the e-mail you give us.", kind: "text" },
  "kon.fName": { pl: "Imię i nazwisko", en: "Full name", kind: "text" },
  "kon.fEmail": { pl: "E-mail", en: "E-mail", kind: "text" },
  "kon.fPhone": { pl: "Telefon (opcjonalnie)", en: "Phone (optional)", kind: "text" },
  "kon.fSubject": { pl: "Temat", en: "Subject", kind: "text" },
  "kon.fMsg": { pl: "Wiadomość", en: "Message", kind: "text" },
  "kon.s1": { pl: "SZKOLENIE", en: "TRAINING", kind: "text" },
  "kon.s2": { pl: "VOUCHER", en: "VOUCHER", kind: "text" },
  "kon.s3": { pl: "EVENT FIRMOWY", en: "CORPORATE EVENT", kind: "text" },
  "kon.s4": { pl: "INNE", en: "OTHER", kind: "text" },
  "kon.send": { pl: "WYŚLIJ WIADOMOŚĆ", en: "SEND THE MESSAGE", kind: "text" },
  "kon.sending": { pl: "WYSYŁAM…", en: "SENDING…", kind: "text" },
  "kon.rodo": { pl: "Wysyłając wiadomość zgadzasz się na kontakt zwrotny w sprawie zapytania.", en: "By sending the message you agree to be contacted back about your enquiry.", kind: "text" },
  "kon.errFill": { pl: "Uzupełnij imię i nazwisko, poprawny e-mail oraz treść wiadomości.", en: "Please fill in your name, a valid e-mail and the message.", kind: "text" },
  "kon.errSend": { pl: "Nie udało się wysłać wiadomości. Spróbuj ponownie lub zadzwoń.", en: "The message could not be sent. Please try again or call us.", kind: "text" },
  "kon.doneTitle": { pl: "LIGHTS OUT — WIADOMOŚĆ WYSŁANA!", en: "LIGHTS OUT — MESSAGE SENT!", kind: "text" },
  "kon.doneSub": { pl: "Dziękujemy! Odezwiemy się na podany adres e-mail najszybciej jak to możliwe.", en: "Thank you! We'll get back to you at the e-mail you provided as soon as possible.", kind: "html" },
  "kon.doneBtn": { pl: "NAPISZ KOLEJNĄ", en: "WRITE ANOTHER", kind: "text" },
  "kon.trackEyebrow": { pl: "GDZIE JEŹDZIMY", en: "WHERE WE DRIVE", kind: "text" },
  "kon.trackTitle": { pl: "NASZE TORY", en: "OUR CIRCUITS", kind: "text" },
  "kon.trackBtn": { pl: "ZOBACZ KALENDARZ", en: "SEE THE CALENDAR", kind: "text" },

  // --- Cennik page (/cennik) — prices come from the CMS, the board is generated ---
  "cen.eyebrow": { pl: "CENY SZKOLEŃ I TRENINGÓW", en: "TRAINING PRICES", kind: "text" },
  "cen.title": { pl: "CENNIK", en: "PRICING", kind: "text" },
  "cen.sub": { pl: "Wszystkie ceny w jednym miejscu — sesje na torze, treningi wyścigowe i wyprawy. Kliknij cenę, aby od razu przejść do rezerwacji.", en: "Every price in one place — track sessions, racing training and trips. Click a price to jump straight into booking.", kind: "html" },
  "cen.boardEyebrow": { pl: "SZKOLENIA JAZDY SPORTOWEJ", en: "SPORT DRIVING TRAINING", kind: "text" },
  "cen.boardTitle": { pl: "CENY SESJI NA TORZE", en: "TRACK SESSION PRICES", kind: "text" },
  "cen.lodz": { pl: "TOR ŁÓDŹ", en: "ŁÓDŹ CIRCUIT", kind: "text" },
  "cen.poznan": { pl: "TOR POZNAŃ", en: "POZNAŃ CIRCUIT", kind: "text" },
  "cen.car": { pl: "SAMOCHÓD", en: "CAR", kind: "text" },
  "cen.book": { pl: "REZERWUJ", en: "BOOK", kind: "text" },
  "cen.ownSub": { pl: "Przyjeżdżasz swoim autem", en: "You bring your own car", kind: "text" },
  "cen.poznanNote": { pl: "* Ceny na Torze Poznań zawierają opłatę za wjazd samochodu na tor (1200 zł netto).", en: "* Poznań prices include the circuit entry fee for the car (1200 zł net).", kind: "text" },
  "cen.sessionNote": { pl: "Pakiet zawiera wykład z teorii jazdy sportowej oraz trening na torze w sesjach 1:1 z instruktorem. Możliwość odwołania rezerwacji do tygodnia przed terminem.", en: "Each package includes the sport-driving theory lecture and 1:1 track training in sessions. You can cancel your booking up to a week before.", kind: "html" },
  "cen.seeMore": { pl: "ZOBACZ SZCZEGÓŁY", en: "SEE THE DETAILS", kind: "text" },
  "cen.ctaEyebrow": { pl: "GOTOWY NA TOR?", en: "READY FOR THE TRACK?", kind: "text" },
  "cen.ctaTitle": { pl: "WYBIERZ AUTO I PAKIET", en: "CHOOSE A CAR AND A PACKAGE", kind: "text" },
  "cen.ctaSub": { pl: "Konfigurator poprowadzi Cię krok po kroku — auto, termin, liczba sesji i płatność.", en: "The configurator walks you through it — car, date, number of sessions and payment.", kind: "html" },
  "cen.ctaBook": { pl: "KONFIGURATOR JAZDY", en: "DRIVE CONFIGURATOR", kind: "text" },



  // --- Wyprawa (trips: Monaco…) ---
  "wy.buy": { pl: "KUP TERAZ", en: "BUY NOW", kind: "text" },
  "wy.seeProgram": { pl: "ZOBACZ PROGRAM", en: "SEE THE PROGRAM", kind: "text" },
  "wy.seeRecap": { pl: "ZOBACZ RELACJĘ", en: "SEE THE RECAP", kind: "text" },
  "wy.pastBadge": { pl: "WYPRAWA ZAKOŃCZONA", en: "TRIP COMPLETED", kind: "text" },
  "wy.recapEyebrow": { pl: "RELACJA", en: "RECAP", kind: "text" },
  "wy.recapTitle": { pl: "TA WYPRAWA JUŻ ZA NAMI", en: "THIS TRIP IS BEHIND US", kind: "text" },
  "wy.recapCta": { pl: "ZAPYTAJ O KOLEJNĄ EDYCJĘ", en: "ASK ABOUT THE NEXT EDITION", kind: "text" },
  "wy.photosSoon": { pl: "ZDJĘCIA Z WYPRAWY POJAWIĄ SIĘ WKRÓTCE", en: "PHOTOS FROM THE TRIP ARE COMING SOON", kind: "text" },
  "wy.progEyebrow": { pl: "W PROGRAMIE", en: "IN THE PROGRAM", kind: "text" },
  "wy.progTitle": { pl: "ATRAKCJE WYPRAWY", en: "TRIP HIGHLIGHTS", kind: "text" },
  "wy.see": { pl: "ZOBACZ", en: "SEE", kind: "text" },
  "wy.optional": { pl: "OPCJA DODATKOWA", en: "OPTIONAL", kind: "text" },
  "wy.mapEyebrow": { pl: "TRASA", en: "THE ROUTE", kind: "text" },
  "wy.route": { pl: "TRASA WYPRAWY", en: "TRIP ROUTE", kind: "text" },
  "wy.mapTitle": { pl: "MAPA WYPRAWY", en: "TRIP MAP", kind: "text" },
  "wy.schedEyebrow": { pl: "DZIEŃ PO DNIU", en: "DAY BY DAY", kind: "text" },
  "wy.schedTitle": { pl: "HARMONOGRAM", en: "SCHEDULE", kind: "text" },
  "wy.pkgTitle": { pl: "PAKIETY WYPRAWY", en: "TRIP PACKAGES", kind: "text" },
  "wy.doneTitle": { pl: "OPŁACONE — WITAMY NA POKŁADZIE!", en: "PAID — WELCOME ABOARD!", kind: "text" },
  "wy.doneSub": { pl: "Dziękujemy! Skontaktujemy się z Tobą i prześlemy wszystkie szczegóły wyprawy.", en: "Thank you! We'll contact you and send all the details of the trip.", kind: "html" },

  // --- Driver2Racer (/produkty/driver2racer) + direct purchase (/zakup) ---
  "d2r.buy": { pl: "KUP TERAZ", en: "BUY NOW", kind: "text" },
  "d2r.buyNow": { pl: "KUP PAKIET TERAZ", en: "BUY THE PACKAGE NOW", kind: "text" },
  "d2r.seePkg": { pl: "ZOBACZ PAKIET", en: "SEE THE PACKAGE", kind: "text" },
  "d2r.sSessions": { pl: "SESJI NA TORZE", en: "TRACK SESSIONS", kind: "text" },
  "d2r.sTitles": { pl: "TYTUŁÓW MISTRZA POLSKI", en: "POLISH CHAMPION TITLES", kind: "text" },
  "d2r.sSim": { pl: "SESJI NA SYMULATORZE", en: "SIMULATOR SESSIONS", kind: "text" },
  "d2r.gainsTitle": { pl: "CO ZYSKASZ, WYBIERAJĄC NASZ PROGRAM?", en: "WHAT DO YOU GAIN FROM OUR PROGRAM?", kind: "text" },
  "d2r.coachEyebrow": { pl: "TRENUJ Z NAJLEPSZYMI", en: "TRAIN WITH THE BEST", kind: "text" },
  "d2r.coachTitle": { pl: "COACHING Z MISTRZEM POLSKI", en: "COACHING WITH A POLISH CHAMPION", kind: "text" },
  "d2r.champion": { pl: "MISTRZ POLSKI", en: "POLISH CHAMPION", kind: "text" },
  "d2r.sessTitle": { pl: "24 SESJE, KTÓRE ZMIENIĄ TWOJĄ JAZDĘ", en: "24 SESSIONS THAT WILL CHANGE THE WAY YOU DRIVE", kind: "text" },
  "d2r.sessSub": { pl: "Program rozpisany etapami — od techniki jazdy sportowej po Porsche 911 i profesjonalny symulator.", en: "The program runs in stages — from sport driving technique to the Porsche 911 and a professional simulator.", kind: "html" },
  "d2r.sessionsWord": { pl: "SESJI TRENINGOWYCH", en: "TRAINING SESSIONS", kind: "text" },
  "d2r.s1": { pl: "STAGE 1 — Alpine / Supra / A45s", en: "STAGE 1 — Alpine / Supra / A45s", kind: "text" },
  "d2r.s2": { pl: "STAGE 2 — Alpine / Supra / A45s", en: "STAGE 2 — Alpine / Supra / A45s", kind: "text" },
  "d2r.s3": { pl: "STAGE 2 — Porsche 911 Carrera 4 GTS", en: "STAGE 2 — Porsche 911 Carrera 4 GTS", kind: "text" },
  "d2r.sim": { pl: "SIMRACING — symulator wyścigowy", en: "SIMRACING — racing simulator", kind: "text" },
  "d2r.fleetEyebrow": { pl: "OKIEŁZNAJ FLOTĘ", en: "TAME THE FLEET", kind: "text" },
  "d2r.fleetCap": { pl: "FLOTA PROGRAMU", en: "THE PROGRAM FLEET", kind: "text" },
  "d2r.telemetry": { pl: "TELEMETRIA — PRĘDKOŚĆ NA OKRĄŻENIU", en: "TELEMETRY — SPEED OVER A LAP", kind: "text" },
  "d2r.fleetTitle": { pl: "SAMOCHODY WYŚCIGOWE, KTÓRE WYZNACZAJĄ STANDARDY", en: "RACE CARS THAT SET THE STANDARD", kind: "text" },
  "d2r.trackEyebrow": { pl: "TWÓJ SPOT TRENINGOWY", en: "YOUR TRAINING GROUND", kind: "text" },
  "d2r.trackTitle": { pl: "TORY WYŚCIGOWE", en: "RACING CIRCUITS", kind: "text" },
  "d2r.stepsTitle": { pl: "TWÓJ PIERWSZY KROK DO ŚWIATA WYŚCIGÓW", en: "YOUR FIRST STEP INTO THE WORLD OF RACING", kind: "text" },
  "d2r.step1.t": { pl: "KONTAKT", en: "CONTACT", kind: "text" },
  "d2r.step1.b": { pl: "Skontaktuj się z nami — odpowiemy na wszystkie Twoje pytania i wspólnie ustalimy, czy program jest dla Ciebie.", en: "Get in touch — we'll answer all your questions and work out together whether the program is right for you.", kind: "html" },
  "d2r.step2.t": { pl: "SPOTKANIE WSTĘPNE", en: "FIRST MEETING", kind: "text" },
  "d2r.step2.b": { pl: "Omówimy Twoje cele i oczekiwania oraz dopasujemy program do Twoich potrzeb.", en: "We'll discuss your goals and expectations and tailor the program to your needs.", kind: "html" },
  "d2r.step3.t": { pl: "PLAN DZIAŁANIA", en: "THE PLAN", kind: "text" },
  "d2r.step3.b": { pl: "Przygotujemy spersonalizowany harmonogram treningów, abyś rozwijał się efektywnie.", en: "We'll prepare a personalised training schedule so you progress efficiently.", kind: "html" },
  "d2r.step4.t": { pl: "START", en: "START", kind: "text" },
  "d2r.step4.b": { pl: "Czas wejść na tor i zacząć pracować nad realizacją swoich ambicji!", en: "Time to get on track and start working towards your ambitions!", kind: "html" },
  "d2r.pkgTitle": { pl: "PAKIET DRIVER2RACER", en: "THE DRIVER2RACER PACKAGE", kind: "text" },
  "d2r.priceLabel": { pl: "CENA PAKIETU", en: "PACKAGE PRICE", kind: "text" },
  "d2r.net": { pl: "netto", en: "net", kind: "text" },
  "d2r.coach": { pl: "COACHING", en: "COACHING", kind: "text" },
  "d2r.buyHint": { pl: "Bez konfiguratora — podajesz dane i płacisz.", en: "No configurator — just your details and payment.", kind: "text" },

  // --- /zakup (direct package purchase) ---
  "zak.eyebrow": { pl: "ZAKUP PAKIETU", en: "BUY THE PACKAGE", kind: "text" },
  "zak.sub": { pl: "Potrzebujemy ich do potwierdzenia zakupu i ustalenia harmonogramu treningów.", en: "We need these to confirm the purchase and agree the training schedule.", kind: "text" },
  "zak.err": { pl: "Uzupełnij poprawnie: imię i nazwisko, e-mail oraz telefon.", en: "Please fill in your name, e-mail and phone correctly.", kind: "text" },
  "zak.missing": { pl: "Ten pakiet nie jest dostępny.", en: "This package is not available.", kind: "text" },
  "zak.doneTitle": { pl: "OPŁACONE — WITAMY W PROGRAMIE!", en: "PAID — WELCOME TO THE PROGRAM!", kind: "text" },
  "zak.doneSub": { pl: "Dziękujemy! Skontaktujemy się z Tobą, aby ustalić harmonogram treningów.", en: "Thank you! We'll contact you to arrange the training schedule.", kind: "html" },

  // --- Ice Driving / Laponia (product page + ice configurator) ---
  "ice.packages": { pl: "PAKIETY I CENY", en: "PACKAGES & PRICES", kind: "text" },
  "ice.pickPkg": { pl: "WYBIERZ PAKIET", en: "CHOOSE A PACKAGE", kind: "text" },
  "ice.buy": { pl: "KUP PAKIET", en: "BUY THE PACKAGE", kind: "text" },
  "ice.day": { pl: "DZIEŃ", en: "DAY", kind: "text" },
  "ice.days": { pl: "DNI", en: "DAYS", kind: "text" },
  "ice.perPerson": { pl: "brutto / osoba", en: "gross / person", kind: "text" },
  "ice.windowNote": { pl: "Terminy dostępne w sezonie:", en: "Dates available this season:", kind: "text" },
  "ice.season": { pl: "SEZON LODOWY", en: "ICE SEASON", kind: "text" },
  "ice.daysNote": { pl: "wybierasz pierwszy dzień — pakiet trwa {n} dni", en: "pick the first day — the package lasts {n} days", kind: "text" },
  "ice.ctaTitle": { pl: "ZOBACZ INNY WYMIAR MOTORSPORTU", en: "SEE MOTORSPORT FROM A NEW ANGLE", kind: "text" },
  "ice.ctaSub": { pl: "Zamarznięte jeziora, opony z kolcami i pełna kontrola nad autem w poślizgu. Wybierz pakiet i zarezerwuj swój termin w Laponii.", en: "Frozen lakes, studded tyres and full control of the car in a slide. Choose a package and book your dates in Lapland.", kind: "html" },
  // configurator
  "ice.bkTitle": { pl: "ICE DRIVING EXPERIENCE", en: "ICE DRIVING EXPERIENCE", kind: "text" },
  "ice.bkSub": { pl: "LAPONIA · KUUSAMO · FINLANDIA", en: "LAPLAND · KUUSAMO · FINLAND", kind: "text" },
  "ice.configTitle": { pl: "KONFIGURATOR LODOWY", en: "ICE CONFIGURATOR", kind: "text" },
  "ice.sPkg": { pl: "PAKIET", en: "PACKAGE", kind: "text" },
  "ice.sCar": { pl: "AUTO", en: "CAR", kind: "text" },
  "ice.pickCar": { pl: "WYBIERZ AUTO", en: "CHOOSE A CAR", kind: "text" },
  "ice.carSub": { pl: "Wybierz samochód, którym chcesz jeździć po zamarzniętym jeziorze — wszystkie startują na oponach z kolcami.", en: "Pick the car you want to drive on the frozen lake — all of them run on studded tyres.", kind: "text" },
  "ice.errCar": { pl: "Wybierz auto.", en: "Choose a car.", kind: "text" },
  "ice.sDate": { pl: "TERMIN", en: "DATES", kind: "text" },
  "ice.sData": { pl: "DANE", en: "DETAILS", kind: "text" },
  "ice.sPay": { pl: "PŁATNOŚĆ", en: "PAYMENT", kind: "text" },
  "ice.pickDate": { pl: "WYBIERZ TERMIN", en: "CHOOSE YOUR DATES", kind: "text" },
  "ice.stay": { pl: "TWÓJ POBYT", en: "YOUR STAY", kind: "text" },
  "ice.persons": { pl: "Liczba osób", en: "Number of people", kind: "text" },
  "ice.personsShort": { pl: "os.", en: "pers.", kind: "text" },
  "ice.total": { pl: "RAZEM", en: "TOTAL", kind: "text" },
  "ice.pay": { pl: "ZAPŁAĆ I ZAREZERWUJ", en: "PAY & BOOK", kind: "text" },
  "ice.freezing": { pl: "ZAMRAŻANIE PŁATNOŚCI…", en: "FREEZING THE PAYMENT…", kind: "text" },
  "ice.doneTitle": { pl: "ZAMROŻONE — OPŁACONE!", en: "FROZEN — PAID!", kind: "text" },
  "ice.thanks": { pl: "Dziękujemy! Twoja rezerwacja Ice Driving Experience jest potwierdzona. Szczegóły wyślemy na podany e-mail.", en: "Thank you! Your Ice Driving Experience booking is confirmed. We'll send the details to your e-mail.", kind: "html" },
  "ice.errPkg": { pl: "Wybierz pakiet.", en: "Choose a package.", kind: "text" },
  "ice.errDate": { pl: "Wybierz termin.", en: "Choose your dates.", kind: "text" },
  "ice.errData": { pl: "Uzupełnij poprawnie: imię i nazwisko, e-mail oraz telefon.", en: "Please fill in your name, e-mail and phone correctly.", kind: "text" },

  // --- Kalendarz page (/kalendarz) — dates come from the CMS "Terminy" tab ---
  "kal.eyebrow": { pl: "TERMINY NA TORACH", en: "DATES ON THE TRACKS", kind: "text" },
  "kal.title": { pl: "KALENDARZ", en: "CALENDAR", kind: "text" },
  "kal.sub": { pl: "Wszystkie nadchodzące szkolenia i wydarzenia Fastline Racing Academy. Wybierz termin, potem auto i pakiet sesji — rezerwacja zajmie chwilę.", en: "Every upcoming Fastline Racing Academy training and event. Pick a date, then a car and a session package — booking takes a moment.", kind: "html" },
  "kal.statTerms": { pl: "NADCHODZĄCYCH TERMINÓW", en: "UPCOMING DATES", kind: "text" },
  "kal.statNext": { pl: "NAJBLIŻSZY TERMIN", en: "NEXT DATE", kind: "text" },
  "kal.statTracks": { pl: "TORY W KALENDARZU", en: "CIRCUITS IN THE CALENDAR", kind: "text" },
  "kal.prev": { pl: "Poprzedni miesiąc", en: "Previous month", kind: "text" },
  "kal.next": { pl: "Następny miesiąc", en: "Next month", kind: "text" },
  "kal.jumpNext": { pl: "NAJBLIŻSZY TERMIN", en: "NEXT DATE", kind: "text" },
  "kal.today": { pl: "DZIŚ", en: "TODAY", kind: "text" },
  "kal.emptyMonth": { pl: "W tym miesiącu nie ma jeszcze terminów.", en: "No dates scheduled this month yet.", kind: "text" },
  "kal.emptyAll": { pl: "Brak zaplanowanych terminów — napisz do nas, a ustalimy termin indywidualnie.", en: "No scheduled dates — write to us and we'll arrange one individually.", kind: "text" },
  "kal.fTime": { pl: "GODZINY", en: "HOURS", kind: "text" },
  "kal.fTrack": { pl: "TOR", en: "CIRCUIT", kind: "text" },
  "kal.fSpots": { pl: "MIEJSC", en: "SPOTS", kind: "text" },
  "kal.fPrice": { pl: "CENA", en: "PRICE", kind: "text" },
  "kal.from": { pl: "od", en: "from", kind: "text" },
  "kal.book": { pl: "ZAREZERWUJ", en: "BOOK NOW", kind: "text" },
  "kal.season": { pl: "SEZON", en: "SEASON", kind: "text" },
  "kal.trip": { pl: "WYPRAWA", en: "TRIP", kind: "text" },
  "kal.see": { pl: "ZOBACZ", en: "SEE", kind: "text" },
  "kal.recap": { pl: "RELACJA", en: "RECAP", kind: "text" },
  "kal.bookHint": { pl: "W kolejnym kroku wybierzesz auto, liczbę sesji i zapłacisz.", en: "Next you'll choose the car, the number of sessions and pay.", kind: "text" },
  "kal.upEyebrow": { pl: "PEŁNA LISTA", en: "THE FULL LIST", kind: "text" },
  "kal.upTitle": { pl: "NADCHODZĄCE TERMINY", en: "UPCOMING DATES", kind: "text" },
  "kal.ctaEyebrow": { pl: "NIE MA PASUJĄCEJ DATY?", en: "NO MATCHING DATE?", kind: "text" },
  "kal.ctaTitle": { pl: "TERMIN USTALIMY INDYWIDUALNIE", en: "WE'LL ARRANGE A DATE FOR YOU", kind: "text" },
  "kal.ctaSub": { pl: "Wybierz auto i pakiet, a my dobierzemy termin na torze pod Ciebie.", en: "Choose a car and a package — we'll arrange the track date around you.", kind: "html" },
  "kal.ctaBook": { pl: "REZERWUJ BEZ DATY", en: "BOOK WITHOUT A DATE", kind: "text" },
  "kal.ctaFleet": { pl: "ZOBACZ FLOTĘ", en: "SEE THE FLEET", kind: "text" },

  // --- stub page (Nasz zespół) ---
  "stub.soon": { pl: "WKRÓTCE", en: "COMING SOON", kind: "text" },
  "stub.team.title": { pl: "NASZ ZESPÓŁ", en: "OUR TEAM", kind: "text" },
  "stub.team.body": { pl: "Poznaj pełny skład instruktorów i zespołu Fastline Racing Academy — ta strona jest w przygotowaniu.", en: "Meet the full roster of Fastline Racing Academy instructors and crew — this page is in preparation.", kind: "html" },
  "stub.back": { pl: "← POWRÓT NA STRONĘ GŁÓWNĄ", en: "← BACK TO HOME", kind: "text" },
};
